selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5100/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/food-express
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: uwF0YxtqlpSXPNSUw8QqJ8vYujTAJIgn
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

